plugins { id 'com.android.application' }

android {
    namespace 'com.hafz.offlinefinance'
    compileSdk 35
    defaultConfig {
        applicationId 'com.hafz.offlinefinance.v7'
        minSdk 23
        targetSdk 35
        versionCode 40
        versionName '7.0'
    }
    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
dependencies {
    implementation 'androidx.biometric:biometric:1.1.0'
}
